version: '3.2'

services:  
  build:
    image: node:14-alpine
    container_name: monorepo-docker
    restart: always
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start